// src/ai/flows/generate-novel-idea.ts
'use server';

/**
 * @fileOverview Generates novel business ideas based on user-provided keywords or problem areas, including a novelty score.
 *
 * - generateNovelIdea - A function that generates novel business ideas.
 * - GenerateNovelIdeaInput - The input type for the generateNovelIdea function.
 * - GenerateNovelIdeaOutput - The return type for the generateNovelIdea function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateNovelIdeaInputSchema = z.object({
  keywords: z
    .string()
    .describe('Keywords or topics to focus the idea generation on.')
    .optional(),
  problemArea: z
    .string()
    .describe('A specific problem area to generate ideas for.')
    .optional(),
});

export type GenerateNovelIdeaInput = z.infer<typeof GenerateNovelIdeaInputSchema>;

const NovelIdeaSchema = z.object({
  idea: z.string().describe('The novel business idea text.'),
  noveltyScore: z.number().min(1).max(10).describe('A score from 1 (common) to 10 (highly novel/unique) indicating the AI\'s assessment of the idea\'s uniqueness.'),
});

const GenerateNovelIdeaOutputSchema = z.object({
  novelIdeas: z
    .array(NovelIdeaSchema)
    .describe('A list of novel business ideas generated by the AI, each with a novelty score.'),
});

export type GenerateNovelIdeaOutput = z.infer<typeof GenerateNovelIdeaOutputSchema>;

export async function generateNovelIdea(input: GenerateNovelIdeaInput): Promise<GenerateNovelIdeaOutput> {
  return generateNovelIdeaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateNovelIdeaPrompt',
  input: {schema: GenerateNovelIdeaInputSchema},
  output: {schema: GenerateNovelIdeaOutputSchema},
  prompt: `You are an expert in identifying novel business opportunities.
  Based on the provided keywords and problem areas, generate a list of 3-5 truly novel business ideas.
  For each idea, also provide a "noveltyScore" between 1 (very common, low novelty) and 10 (highly unique, high novelty).
  Avoid ideas that are commonly suggested or already saturated in the market.

  {{#if keywords}}Keywords: {{{keywords}}}{{/if}}
  {{#if problemArea}}Problem Area: {{{problemArea}}}{{/if}}

  Focus on ideas with the potential to generate significant revenue daily.

  Return the ideas as a list of objects, where each object contains an 'idea' (string) and a 'noveltyScore' (number 1-10).
  Example format for one idea: { "idea": "A drone-based window cleaning service for skyscrapers", "noveltyScore": 7 }
  `,
});

const generateNovelIdeaFlow = ai.defineFlow(
  {
    name: 'generateNovelIdeaFlow',
    inputSchema: GenerateNovelIdeaInputSchema,
    outputSchema: GenerateNovelIdeaOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output || !Array.isArray(output.novelIdeas)) {
        // Ensure a valid array is returned, even if empty
        return { novelIdeas: [] };
    }
     // Validate and clamp novelty scores
    const validatedIdeas = output.novelIdeas.map(item => ({
      idea: item.idea || "AI failed to provide idea text.",
      noveltyScore: Math.min(10, Math.max(1, Number(item.noveltyScore) || 5)), // Default to 5 if invalid
    }));
    return { novelIdeas: validatedIdeas };
  }
);