name: Deploy to Contabo VPS

on:
  push:
    branches:
      - master # Or 'main' if that's your default branch

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            # Navigate to the correct directory
            cd /root/ai-agent-idea-incubator

            # --- Clean up and pull latest code ---
            echo "--- Clean up and pull latest code ---"
            # Ensure the local repository is clean and matches the remote
            git fetch origin
            git reset --hard origin/master
            # Clean up any untracked files and directories
            git clean -fd

            # --- Install dependencies and build ---
            echo "--- Installing dependencies and building ---"
            # Load Node.js environment via NVM
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use --lts
            
            # Remove old build directories for a fresh start
            rm -rf .next
            rm -rf node_modules
            
            pnpm install
            pnpm build

            # --- Start/reload application with PM2 ---
            echo "--- Starting/reloading application with PM2 ---"
            APP_NAME="idea-incubator"
            # Check if the app is already running and reload it, otherwise start it
            if pm2 describe "$APP_NAME" > /dev/null; then
              pm2 reload "$APP_NAME"
            else
              # Use the 'start' command from package.json
              pm2 start "pnpm" --name "$APP_NAME" -- start
            fi
            
            pm2 save
            
            echo "✅ Deployment complete!"